"""
Authorized-device store (``authfile.txt``) and discovery of connected devices.

What changed relative to v1, and why:

* Device discovery no longer shells out to ``wmic``.  WMIC was deprecated in
  Windows 10 21H1 and is *removed* from current Windows 11 builds, so the old
  ``subprocess.check_output('wmic ...')`` call failed on any freshly installed
  machine.  The same information now comes from WMI through pywin32.
* Device names are matched on "mass storage" rather than the exact string
  "USB Mass Storage Device", because UASP drives report themselves as
  "USB Attached SCSI (UAS) Mass Storage Device" (v1 silently ignored them).
* An empty or unidentified device id is denied.  The v1 reader used
  ``if serial_number in auth_device``, and an empty string matches everything -
  so a device Windows could not name was reported as authenticated.
"""

from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Iterable, List, Optional, Sequence

import config
import encrypt

log = logging.getLogger(__name__)

#: ClassGuid of the USB device class - the same filter the v1 wmic command used.
USB_CLASS_GUID = "{36fc9e60-c465-11cf-8056-444553540000}"

#: Driver names that identify a USB mass-storage device (UASP included).
MASS_STORAGE_HINTS = ("mass storage",)

#: Prefixes a Windows PnP device id must have to be considered a USB storage id.
DEVICE_ID_PREFIXES = ("USB\\", "USBSTOR\\")

#: Written to the top of a freshly created authfile.
AUTHFILE_HEADER = (
    "# Authorized USB devices - one fingerprint per line.\n"
    "# Generated by the USB Authentication Tool; blank lines and '#' comments are ignored.\n"
)


def _wmi_service():
    """Connect to the local WMI namespace (import kept local: tests run anywhere)."""
    import win32com.client

    return win32com.client.GetObject("winmgmts:")


def _query(service, where: str):
    return service.ExecQuery(f"SELECT DeviceID, Name FROM Win32_PnPEntity WHERE {where}")


def current_device_ids() -> List[str]:
    """PnP DeviceIDs of every connected USB mass-storage device (possibly empty)."""
    try:
        service = _wmi_service()
    except Exception as exc:
        log.error("WMI is unavailable (%s) - no device can be verified", exc)
        return []

    device_ids: List[str] = []
    # The ClassGuid filter mirrors the original wmic query; the Name filter is a
    # fallback for drivers that do not report the USB class GUID at all.
    for where in (f"ClassGuid='{USB_CLASS_GUID}'", "Name LIKE '%Mass Storage%'"):
        try:
            entities = _query(service, where)
        except Exception as exc:
            log.warning("WMI query failed (%s): %s", where, exc)
            continue

        for entity in entities:
            device_id = str(getattr(entity, "DeviceID", "") or "").strip()
            name = str(getattr(entity, "Name", "") or "").lower()
            if not device_id or not device_id.upper().startswith(DEVICE_ID_PREFIXES):
                continue
            if not any(hint in name for hint in MASS_STORAGE_HINTS):
                continue
            if device_id not in device_ids:
                device_ids.append(device_id)

        if device_ids:
            break

    log.debug("connected USB mass-storage devices: %s", device_ids)
    return device_ids


def authfile_path(settings: Optional[config.Settings] = None) -> Path:
    """Path of the authorized-device file for the current configuration."""
    return (settings or config.load_settings()).authfile


def ensure_authfile(path: Path, header: bool = True) -> bool:
    """Create an empty authfile when it is missing. Returns ``True`` if created.

    v1 opened ``authfile.txt`` for reading before it ever wrote to it, so the very
    first run on a clean machine raised ``FileNotFoundError``.
    """
    if path.exists():
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(AUTHFILE_HEADER if header else "", encoding="utf-8")
    log.info("created %s", path)
    return True


def read_authorized(path: Optional[Path] = None) -> List[str]:
    """Fingerprints currently listed in the authfile (comments and blanks skipped)."""
    target = path or authfile_path()
    if not target.exists():
        log.info("authfile %s does not exist yet - every device is unknown", target)
        return []
    try:
        lines = target.read_text(encoding="utf-8").splitlines()
    except OSError as exc:
        log.error("cannot read %s: %s", target, exc)
        return []
    return encrypt.read_entries(lines)


def write_authorized(entries: Sequence[str], path: Optional[Path] = None) -> Path:
    """Replace the authfile atomically (temporary file + rename).

    An interrupted or concurrent write can therefore never leave a half-written
    whitelist behind, which the v1 read-modify-write sequence could.
    """
    target = path or authfile_path()
    target.parent.mkdir(parents=True, exist_ok=True)
    body = AUTHFILE_HEADER + "".join(f"{entry}\n" for entry in entries)
    temporary = target.with_name(f"{target.name}.tmp")
    temporary.write_text(body, encoding="utf-8")
    os.replace(temporary, target)
    return target


def authorized(fingerprints: Iterable[str], settings: Optional[config.Settings] = None) -> bool:
    """True when at least one fingerprint is whitelisted.

    Fails closed: no fingerprints, or an empty authfile, means "not authorized".
    """
    candidates = [
        value for value in (encrypt.normalize_entry(item) for item in fingerprints) if value
    ]
    if not candidates:
        log.warning("no usable device fingerprint - denying")
        return False

    stored = read_authorized(authfile_path(settings))
    if not stored:
        return False
    return any(encrypt.is_match(stored, candidate) for candidate in candidates)


def authorize_devices(
    device_ids: Iterable[str], settings: Optional[config.Settings] = None
) -> List[str]:
    """Store fingerprints for the given device ids. Returns the entries added."""
    settings = settings or config.load_settings()
    target = authfile_path(settings)
    fingerprints = [
        value
        for value in (encrypt.device_fingerprint(item, settings) for item in device_ids)
        if value
    ]
    if not fingerprints:
        log.warning("refusing to authorize: no usable device id was supplied")
        return []

    stored = read_authorized(target)
    added = [value for value in fingerprints if not encrypt.is_match(stored, value)]
    if not added:
        log.debug("every supplied device is already authorized")
        return []

    ensure_authfile(target)
    write_authorized(stored + added, target)
    log.info("authorized %d device(s) in %s", len(added), target)
    return added


def connected(settings: Optional[config.Settings] = None) -> List[str]:
    """Authorize every USB mass-storage device connected right now.

    Kept under its original name so v1 callers (``import auth; auth.connected()``)
    continue to work; new code should call :func:`authorize_devices` with an
    explicit device list.
    """
    return authorize_devices(current_device_ids(), settings)
